Pr/behat test
mangoweb-sylius/SyliusSortingPlugin pull request #1
Opened 2019-11-21 13:04 UTC by eliatib

2019-11-21 15:25 UTC, ondrej-kuhnel requested changes

2019-11-21 15:25 UTC, ondrej-kuhnel commented on .travis.yml
uncomment `- bin/behat`

2019-11-25 08:19 UTC, eliatib commented on .travis.yml
DONE

2019-11-26 10:27 UTC, ondrej-kuhnel requested changes

2019-11-26 10:27 UTC, ondrej-kuhnel commented on .idea/.gitignore
> +# Default ignored files
remove `.idea` folder

2019-11-26 10:27 UTC, ondrej-kuhnel commented on behat.yml.dist
> +                    selenium2:
I don't think you're using selenium?

2019-11-26 10:27 UTC, ondrej-kuhnel commented on features/managing_sorting/disable_product.feature
> +@sorting
Join both feature files

2019-11-26 10:27 UTC, ondrej-kuhnel commented on features/managing_sorting/disable_product.feature
> +    When I open the "mens_jeans" taxon page
taxon sorting page?

2019-11-26 10:27 UTC, ondrej-kuhnel commented on features/managing_sorting/disable_product.feature
> +  Scenario: Being able to sort products
You mean see disabled products?

2019-11-26 10:27 UTC, ondrej-kuhnel commented on features/managing_sorting/sort_products.feature
> +    When I open the "mens_jeans" taxon page
It should start with GIVEN

2019-11-26 10:27 UTC, ondrej-kuhnel commented on features/managing_sorting/disable_product.feature
> +    When I open the "mens_jeans" taxon page
It should start with GIVEN

2019-11-26 10:27 UTC, ondrej-kuhnel commented on tests/Behat/Pages/Admin/Sorting/SortingPageInterface.php
> +	public function saveSorting();
missing return types

2019-11-26 10:27 UTC, ondrej-kuhnel commented on features/managing_sorting/disable_product.feature
> +Feature: Sort products note
note?

2019-11-26 10:27 UTC, ondrej-kuhnel commented on features/managing_sorting/disable_product.feature
> +  In order to sort products in the store
in category

2019-11-26 10:27 UTC, ondrej-kuhnel commented on features/managing_sorting/sort_products.feature
> +    When I open the "mens_jeans" taxon page
Add after this `And I should see the "Slim fit classic" in 1st position` (yes duplicate :))

2019-11-26 12:27 UTC, eliatib commented on .idea/.gitignore
> +# Default ignored files
DONE

2019-11-26 12:30 UTC, eliatib commented on behat.yml.dist
> +                    selenium2:
it's from the standard behat.yml.dist that I used, I removed all selenium parts

2019-11-26 12:30 UTC, eliatib commented on features/managing_sorting/disable_product.feature
> +@sorting
DONE

2019-11-26 12:30 UTC, eliatib commented on features/managing_sorting/disable_product.feature
> +    When I open the "mens_jeans" taxon page
yes, I changed it

2019-11-26 12:30 UTC, eliatib commented on features/managing_sorting/disable_product.feature
> +  Scenario: Being able to sort products
yes, I changed it

2019-11-26 12:31 UTC, eliatib commented on features/managing_sorting/sort_products.feature
> +    When I open the "mens_jeans" taxon page
DONE

2019-11-26 12:31 UTC, eliatib commented on tests/Behat/Pages/Admin/Sorting/SortingPageInterface.php
> +	public function saveSorting();
DONE

2019-11-26 12:31 UTC, eliatib commented on features/managing_sorting/disable_product.feature
> +  In order to sort products in the store
DONE

2019-11-26 12:32 UTC, eliatib commented on features/managing_sorting/disable_product.feature
> +Feature: Sort products note
it's an oversight, I removed it,

2019-11-26 12:32 UTC, eliatib commented on features/managing_sorting/disable_product.feature
> +    When I open the "mens_jeans" taxon page
DONE

2019-11-26 13:33 UTC, ondrej-kuhnel requested changes

2019-11-26 13:33 UTC, ondrej-kuhnel commented on features/managing_sorting/sort_products_and_show_disable_products.feature
> +	Given I open the "mens_jeans" taxon sorting page
add spaces (format it)

2019-11-26 13:53 UTC, eliatib commented on features/managing_sorting/sort_products_and_show_disable_products.feature
> +	Given I open the "mens_jeans" taxon sorting page
DONE

2019-11-26 14:00 UTC, ondrej-kuhnel approved these changes

2019-11-26 14:01 UTC, merged